"""Initial

Revision ID: fce710e342c9
Revises: c73f542b8dec
Create Date: 2025-09-02 17:54:27.833499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fce710e342c9'
down_revision: Union[str, Sequence[str], None] = 'c73f542b8dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_value'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_table('brands')
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name_uz', sa.VARCHAR(), nullable=False),
    sa.Column('name_ru', sa.VARCHAR(), nullable=False),
    sa.Column('name_en', sa.VARCHAR(), nullable=False),
    sa.Column('description_uz', sa.TEXT(), nullable=True),
    sa.Column('description_ru', sa.TEXT(), nullable=True),
    sa.Column('description_en', sa.TEXT(), nullable=True),
    sa.Column('characteristic_uz', sa.TEXT(), nullable=True),
    sa.Column('characteristic_ru', sa.TEXT(), nullable=True),
    sa.Column('characteristic_en', sa.TEXT(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('brand_id', sa.INTEGER(), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('images', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brands',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('image', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=1)
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.VARCHAR(), nullable=True),
    sa.Column('name_uz', sa.VARCHAR(), nullable=True),
    sa.Column('name_ru', sa.VARCHAR(), nullable=True),
    sa.Column('name_en', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_value'), 'categories', ['value'], unique=1)
    # ### end Alembic commands ###
